### ISSUE TITLE
getRoutes() and getEnvironments() failing

### ISSUE THREAD

**Issue by vincenzo** [platformsh/platformsh-client-js#5] opened 2018-03-15 14:41 UTC
I tried those two, but this issue may not be limited to them. When calling `getRoutes()` or `getEnvironments()` one gets no results back and the following warnings: 

```
(node:1086) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token < in JSON at position 0

(node:1086) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The first warning makes me think the API call is getting back HTML or similar markup instead of the expected JSON?

**Comment by ydeshayes** [comment] 2018-03-15 14:42
Hello,

can you give me the project id?

**Comment by vincenzo** [comment] 2018-03-15 14:44
It's `qfxph7o5zngfi`. Bear in mind it's not on Platform's public region.

**Comment by ydeshayes** [comment] 2018-03-15 17:32
Thanks for the informations, 

seems like we have an issue with our API, 

I will get back to you when it's fixed.

**Comment by vincenzo** [comment] 2018-03-15 18:14
@ydeshayes However, the official `platform-cli` is working just fine.

**Comment by ydeshayes** [comment] 2018-03-16 08:08
Hello,

It should be fixed now, can you test on your side?

Tanks

**Comment by vincenzo** [comment] 2018-03-16 09:08
@ydeshayes It does indeed work now. 

It leaves puzzled as to why this client wasn't working, but https://github.com/platformsh/platformsh-cli was instead.

**Comment by ydeshayes** [comment] 2018-03-16 09:27
The CLI and this library are not using the same API, that's why it was working on the CLI.

**Comment by vincenzo** [comment] 2018-03-16 11:16
I see. Are you sure your API hasn't gone south again? It worked first thing this morning, now I am getting this: 

```
(node:468) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): #<Object>
(node:468) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ydeshayes** [comment] 2018-03-16 11:21
I can't reproduce, can I see your code?

**Comment by vincenzo** [comment] 2018-03-16 11:28
You can't reproduce because now it's working again... Note: my code hasn't changed once in all this...

**Comment by ydeshayes** [comment] 2018-03-16 11:33
Do you create the `Client` instance once for you're all app? I thinking about a token timeout, we never tested that on the server side.

**Comment by vincenzo** [comment] 2018-03-16 11:35
Right now it's just a testing script I relaunch for each test. So `Client` is created fresh each run, used once, done. 

But I do actually intend to do what you're saying once I start integrating this in my app.

**Comment by ydeshayes** [comment] 2018-03-16 11:38
I'm testing the refresh of the token right now.

If you are starting fresh at every run, I will see if we have fails in our calls.

I will get back to you when I've got some responses.

**Comment by ydeshayes** [comment] 2018-03-16 12:17
In the meantime, if you have the same issue, can you post me a message on this thread?

Thanks for your help

**Comment by vincenzo** [comment] 2018-03-16 16:41
The issue has returned (again, code hasn't changed). The difference now is that it takes a while before it comes back with the warnings from https://github.com/platformsh/platformsh-client-js/issues/5#issuecomment-373683430

**Comment by ydeshayes** [comment] 2018-03-16 18:01
Thanks for your informations again. 

I was able to get more logs and we found an other problem in our API.
We are trying to fix it as fast as possible, it's on our top priority right now.

Thanks again for your patience.

**Comment by vincenzo** [comment] 2018-03-19 07:59
@ydeshayes Let me know of any development on this one. 

You still positive that the official CLI uses a different API? As I dug into the code, I seemed to understand that the CLI uses `platformsh-client-php`, which seems to do the same thing as this one.

Yet all works from there.

**Comment by ydeshayes** [comment] 2018-03-20 07:41
A fix was deployed tonight, let me know if it fix your problems.

**Comment by vincenzo** [comment] 2018-03-20 09:35
Doesn't work, mate. 
Yet, it does work when I use the API directly (I've been doing that since yesterday).

**Comment by ydeshayes** [comment] 2018-03-20 09:46
Ok the deployment of the fix was delayed... I will post you a message when it's on production.

**Comment by vincenzo** [comment] 2018-03-20 09:47
@ydeshayes I appreciate you guys working on this, but I am still a bit puzzled as to why the API needs fixing, when I am actually using the same api as this client both via `cURL` and via `node-fetch`, and it works just fine...

**Comment by ydeshayes** [comment] 2018-03-20 10:16
The javascript library is using a new proxy API that resolve the location of the project for us, do caching etc... This library and this new proxy API are very alpha. The bug you found is inside this new proxy API. The CLI and other platformsh products are not using these alpha API and library yet.

**Comment by vincenzo** [comment] 2018-03-20 10:33
I have extracted my calls from this JS client... 
Anyway, all of a sudden my cURL requests have stopped working... which btw I'd rather prefer doing that way as my requirement is to prepare environment variables once and for all, rather than querying from the Node app itself...

**Comment by pjcdawkins** [comment] 2018-03-20 20:02
> all of a sudden my cURL requests have stopped working

This may be a side-effect of our renewing the TLS certificates for some `*.platform.sh` domains yesterday (e.g. `eu.platform.sh`, `us.platform.sh`). I think the new certificates were initially deployed without the intermediate chain files, so some clients would fail to connect.

**Closed** 2018-05-09 13:11 UTC
